In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns 
from sklearn.linear_model import SGDClassifier

### SimpleImputer

In [2]:
from sklearn.impute import SimpleImputer

In [4]:
X= np.array([[10,3],
          [0,4],
          [5,3],
          [np.nan, 3]])

In [7]:
impute = SimpleImputer(missing_values= np.nan, strategy= 'mean')


impute.fit_transform(X)

array([[10.,  3.],
       [ 0.,  4.],
       [ 5.,  3.],
       [ 5.,  3.]])

### KNNImputer

In [8]:
from sklearn.impute import KNNImputer

In [9]:
x= np.array([[1,100],
          [2,30],
          [3,15],
          [np.nan, 20]])

In [10]:
imputer = KNNImputer(n_neighbors= 1)
imputer.fit_transform(x)

array([[  1., 100.],
       [  2.,  30.],
       [  3.,  15.],
       [  3.,  20.]])

### MissingIndicator

In [11]:
from sklearn.impute import MissingIndicator

In [12]:
x= np.array([[1,100],
          [2,30],
          [3,15],
          [np.nan, np.nan]])

In [13]:
 MissingIndicator().fit_transform(x)

array([[False, False],
       [False, False],
       [False, False],
       [ True,  True]])